#
# All Docker related files with the exception of this one reside in the
# "docker" folder to unclutter the top level project directory.
#
# IMPORTANT:
#
# Before running docker-compose up be sure to copy "docker/django-env.example.vars"
# into "docker/django-env.vars" and update the necessary environment variables
# accordingly.
#
version: '2.3'
services:
  haproxy:
    image: eeacms/haproxy
    restart: always
    depends_on:
      - web
    ports:
      - "8080:5000"
      - "1936:1936"
    environment:
      FRONTEND_PORT: 5000
      BACKENDS: "web"
      BALANCE: "roundrobin"
      DNS_ENABLED: "true"
      LOG_LEVEL: "info"

  web:
    command: bash -c "scripts/init-server.sh /dev/stderr discovery-postgresql 5432 && waitress-serve --expose-tracebacks --port=80 discovery.wsgi:application"
    scale: 3
    depends_on:
      - postgresql
      - redis
    links:
      - postgresql:discovery-postgresql
      - redis:discovery-redis
    extends:
      file: docker/docker-compose.base.yml
      service: django

  worker:
    command: bash -c "celery -A discovery worker --loglevel=info --concurrency=2"
    restart: always
    scale: 2
    depends_on:
      - web
    links:
      - postgresql:discovery-postgresql
      - redis:discovery-redis
    extends:
      file: docker/docker-compose.base.yml
      service: django

  scheduler:
    command: bash -c "celery -A discovery beat --loglevel=info"
    restart: always
    depends_on:
      - web
    links:
      - postgresql:discovery-postgresql
      - redis:discovery-redis
    extends:
      file: ./docker/docker-compose.base.yml
      service: django

  postgresql:
    image: postgres:9.3
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - discovery-data:/var/lib/postgresql
    extends:
      file: docker/docker-compose.base.yml
      service: db

  redis:
    image: redis:3.2
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - discovery-queue:/data
    extends:
      file: docker/docker-compose.base.yml
      service: queue

volumes:
  discovery-data:
    external: false

  discovery-queue:
    external: false
