#
# This file contains default settings for the Vagrant development environment.
#
# If you need to override any of these configurations on your own platform then
# copy this file into a "vagrant-config.yml" in the root project directory
# (directory of this file) and your overrides will take effect on the next
# vagrant up or reload.
#
server_name: 'discovery-dev'
box_name: 'ubuntu/trusty64'
cpus: 2
memory_size: 2048
web_port: 8080
db_port: 5432
queue_port: 6379
copy_ssh: false
copy_gitconfig: true
copy_vimrc: false
copy_profile: false
copy_bash_aliases: false
copy_bashrc: false
