version: '2.3'
services:
  db:
    environment:
      POSTGRES_USER: discovery
      POSTGRES_PASSWORD: discovery
      POSTGRES_DB: discovery

  queue:
    command: redis-server --requirepass discovery

  django:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    env_file:
      - django-env.vars
    volumes:
      - ..:/discovery
    environment:
      # What CloudFoundry gives us...
      DATABASE_URL: postgres://discovery:discovery@discovery-postgresql:5432/discovery
      VCAP_SERVICES: >-
        {
          "aws-rds": [
            {
              "credentials": {
                "uri": "postgres://discovery:discovery@discovery-postgresql:5432/discovery",
                "host": "discovery-postgresql",
                "port": "5432",
                "username": "discovery",
                "password": "discovery",
                "db_name": "discovery"
              },
              "label": "aws-rds",
              "name": "discovery-db",
              "tags": [
                "database",
                "RDS",
                "postgresql"
              ]
            }
          ],
          "redis32": [
            {
              "credentials": {
                "uri": "redis://:discovery@discovery-redis:6379",
                "hostname": "discovery-redis",
                "port": "6379",
                "password": "discovery"
              },
              "label": "redis32",
              "name": "discovery-redis",
              "tags": [
                "redis32",
                "redis"
              ]
            }
          ]
        }
