version: '2'
services:
  db:
    environment:
      POSTGRES_USER: oasis
      POSTGRES_PASSWORD: oasis
      POSTGRES_DB: oasis

  django:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    env_file:
      - django-env.vars
    volumes:
      - ..:/discovery
      - ~/.ssh:/root/.ssh
      - ~/.gitconfig:/root/.gitconfig
      - ~/.bashrc:/root/.bashrc
      - ~/.profile:/root/.profile
    environment:
      # What CloudFoundry gives us...
      DATABASE_URL: postgres://oasis:oasis@discovery-postgresql:5432/oasis
      VCAP_SERVICES: >-
        {
          "aws-rds": [
            {
              "credentials": {
                "uri": "postgres://oasis:oasis@discovery-postgresql:5432/oasis",
                "host": "discovery-postgresql",
                "port": "5432",
                "username": "oasis",
                "password": "oasis",
                "db_name": "oasis"
              },
              "label": "aws-rds",
              "name": "discovery-db",
              "tags": [
                "database",
                "RDS",
                "postgresql"
              ]
            }
          ],
          "redis32": [
            {
              "credentials": {
                "uri": "redis://discovery-redis:6379",
                "hostname": "discovery-redis",
                "port": "6379",
                "password": "junk"
              },
              "label": "redis32",
              "name": "discovery-redis",
              "tags": [
                "redis32",
                "redis"
              ]
            }
          ]
        }
